# Generated by Django 3.1.5 on 2021-02-09 11:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_auto_20210209_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='total_working_day',
            new_name='total_working_days',
        ),
        migrations.RenameField(
            model_name='historicalemployee',
            old_name='total_working_day',
            new_name='total_working_days',
        ),
        migrations.AlterField(
            model_name='department',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 9, 16, 0, 27, 990399)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 9, 16, 0, 27, 990399)),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 9, 16, 0, 27, 990399)),
        ),
    ]
